on: push
name: deploy
jobs:
        deploy:
                name: deploy to server
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@master
                        - name: build and push to docker
                          uses: docker/build-push-action@v1
                          with:
                                  username: ${{ secrets.DOCKER_USERNAME }}
                                  password: ${{ secrets.DOCKER_PASSWORD }}
                                  repository: ${{ github.repository  }}
                                  tag_with_ref: true
                                  tag_with_sha: true
                                  tags: ${{ github.sha }}
                        
                        - name: copy file via ssh password
                          uses: appleboy/scp-action@master
                          with:
                                
                                  host: ${{ secrets.MT_HOST }}
                                  username: ${{ secrets.MT_USER }}
                                  password: ${{ secrets.MT_PASS }}
                                  port: ${{ secrets.MT_PORT }}
                                  source: "index.html,css,js,img"
                                  target: "front-mot-test1"

                        - name: ssh pipelines
                          uses: cross-the-world/ssh-pipeline@master
                          env: 

                                MESSAGE: "container updated and container 2 created"     
                                DOCKER_IMAGE: ${{ github.repository }}
                                CONTAINER: ${{ secrets.CONTAINER }}
                                NEW_PORT: ${{ secrets.NEW_PORT  }}

                          with:
                               
                                host: ${{ secrets.MT_HOST }}
                                user: ${{ secrets.MT_USER }}
                                pass: ${{ secrets.MT_PASS }}
                                port: ${{ secrets.MT_PORT }}
                                connect_timeout: 10s
                                script: |
                                  docker pull $DOCKER_IMAGE
                                  docker container ls -aq | xargs --no-run-if-empty docker container rm -f
                                  docker run --name $CONTAINER -d -p $NEW_PORT:80 --restart always $DOCKER_IMAGE
                                  docker run --name $CONTAINER2 -d -v front-mot-test1:/usr/share/nginx/html -p $NEW_PORT2:80 --restart always $DOCKER_IMAGE2 &>log.txt
                                  date > test.txt
                                  echo $MESSAGE >> test.txt

